.TH PLATES 1 "MAY 17, 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
plates \- an OpenALPR training utility to manually find and mark license plates on photos.
.SH SYNOPSIS
.B plates [--plates <YAML files>]
.br
.SH DESCRIPTION
OpenALPR is an open source Automatic License Plate Recognition library written
in C++ with bindings in C#, Java, Node.js, Go, and Python. The library analyzes
images and video streams to identify license plates. The output is the text
representation of any license plate characters.

The purpose of this applications is to train OpenALPR to find license plates.

See https://github.com/openalpr/openalpr for more.
.SH AUTHOR
plates was written by Dmitry Baryshev.
.PP
This manual page was written by Dmitry Baryshev <dmitrymq@gmail.com>,
for the Debian project (but may be used by others).
